---
- name: End-to-End Patching with Pre & Post Checks + Organized Log Collection
  hosts: all
  become: true
  gather_facts: true
  serial: 25%

  vars:
    report_dir: /home/devops
    pre_script: ./precheck.sh
    post_script: ./postcheck.sh
    do_reboot: true
    # <-- controller (Ansible machine) वर reports ठेवण्यासाठी base folder
    base_local_dir: "{{ playbook_dir }}/pching"

  pre_tasks:
    - name: Ensure report directory exists on target
      file:
        path: "{{ report_dir }}"
        state: directory
        mode: "0755"

    # (NEW) controller वर base dir तयार/मालकी सेट — sudo सह
    - name: Ensure base report folder exists on controller
      delegate_to: localhost
      become: true
      file:
        path: "{{ base_local_dir }}"
        state: directory
        owner: "{{ lookup('env','USER') | default('devops', true) }}"
        group: "{{ lookup('env','USER') | default('devops', true) }}"
        mode: "0755"

  tasks:
    - name: Run Pre-check script
      script: "{{ pre_script }}"
      environment:
        OUTDIR: "{{ report_dir }}"
      tags: [precheck]

    - name: Apply updates on RHEL systems
      dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"
      tags: [patch]

    - name: Apply updates on Debian/Ubuntu systems
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"
      tags: [patch]

    - name: Reboot if enabled
      reboot:
        reboot_timeout: 1800
      when: do_reboot | bool
      tags: [reboot]

    - name: Run Post-check script
      script: "{{ post_script }}"
      environment:
        OUTDIR: "{{ report_dir }}"
      tags: [postcheck]

    # -------- Fetch section (fixed) --------
    - name: Set run date (YYYY-MM-DD)
      set_fact:
        run_date: "{{ ansible_date_time.date }}"

    - name: Find generated report files on target
      find:
        paths: "{{ report_dir }}"
        patterns:
          - "precheck_*.txt"
          - "postcheck_*.txt"
        file_type: file
      register: report_files

    # (CHANGED) host/date folder create — sudo on controller, so chown works
    - name: Create per-host/date folder on controller
      delegate_to: localhost
      become: true
      file:
        path: "{{ base_local_dir }}/{{ inventory_hostname }}/{{ run_date }}"
        state: directory
        owner: "{{ lookup('env','USER') | default('devops', true) }}"
        group: "{{ lookup('env','USER') | default('devops', true) }}"
        mode: "0755"

    - name: Fetch reports into controller folder
      fetch:
        src: "{{ item.path }}"
        dest: "{{ base_local_dir }}/{{ inventory_hostname }}/{{ run_date }}/"
        flat: true
      loop: "{{ report_files.files }}"
